// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindKey(arg1) {
  return window['go']['main']['App']['BindKey'](arg1);
}

export function CenterOverlay() {
  return window['go']['main']['App']['CenterOverlay']();
}

export function DismissError() {
  return window['go']['main']['App']['DismissError']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Preview() {
  return window['go']['main']['App']['Preview']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ResetDefaults() {
  return window['go']['main']['App']['ResetDefaults']();
}

export function StopPreview() {
  return window['go']['main']['App']['StopPreview']();
}

export function ToggleMode() {
  return window['go']['main']['App']['ToggleMode']();
}

export function ToggleMove() {
  return window['go']['main']['App']['ToggleMove']();
}

export function ToggleOverlay() {
  return window['go']['main']['App']['ToggleOverlay']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function Weapons() {
  return window['go']['main']['App']['Weapons']();
}
