// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function UpdateSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3);
}
