// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {pattern} from '../models';

export function BindKey(arg1:string):Promise<main.Snapshot>;

export function CenterOverlay():Promise<main.Snapshot>;

export function GetState():Promise<main.Snapshot>;

export function Preview():Promise<main.Snapshot>;

export function Quit():Promise<void>;

export function SavePosition():Promise<void>;

export function StopPreview():Promise<void>;

export function ToggleMode():Promise<main.Snapshot>;

export function ToggleMove():Promise<main.Snapshot>;

export function ToggleOverlay():Promise<main.Snapshot>;

export function UpdateSettings(arg1:main.Settings):Promise<main.Snapshot>;

export function Weapons():Promise<Array<pattern.Weapon>>;
