// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CenterWindow() {
  return window['go']['main']['App']['CenterWindow']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Preview() {
  return window['go']['main']['App']['Preview']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SavePosition() {
  return window['go']['main']['App']['SavePosition']();
}

export function StopPreview() {
  return window['go']['main']['App']['StopPreview']();
}

export function ToggleMode() {
  return window['go']['main']['App']['ToggleMode']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
