// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings():Promise<Record<string, any>>;

export function UpdateSettings(arg1:string,arg2:number):Promise<void>;
